services:
  frontend:
    image: akhilballa112/chat-app:frontend    # change
    restart: always
    ports:
      - "3000:3000"
    environment:
      REACT_APP_CLOUDINARY_CLOUD_NAME: dc5tnb82m       # change
      REACT_APP_BACKEND_URL: http://localhost:8080  
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: akhilballa112/chat-app:backend         # change
    restart: always
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://localhost:27017/
      JWT_SECRET_KEY: jhdcjhsdvchjsdhbfasdgbvs    
      FRONTEND_URL: http://localhost:3000
      PORT: 8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
