services:
  frontend:
    image: akhilballa112/chat-app:frontend-35    
    container_name: chat-frontend
    restart: always
    ports:
      - "3000:80"
    environment:
      REACT_APP_CLOUDINARY_CLOUD_NAME: dc5tnb82m       
      REACT_APP_BACKEND_URL: http://localhost:8081  
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: akhilballa112/chat-app:backend-35      
    container_name: chat-backend
    restart: always
    ports:
      - "8081:8080"
    environment:
      MONGODB_URI: mongodb://localhost:27017/
      JWT_SECRET_KEY: jhdcjhsdvchjsdhbfasdgbvs    
      FRONTEND_URL: http://localhost:3000
      PORT: 8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


# finally done with project akjdnfkjasdnkjad